### ISSUE TITLE
passing props from server to client.

### ISSUE THREAD

**Issue by sharmam1** [rherwig/template-react-16-ssr#25]
How do i pass my api data from server to client as props and,
is it advisable to pass API fetch data from server to client and re-use it to render component.
Note: not using redux

**Comment by rherwig** [comment]
Yes, it is strongly advised to use prefetched data from the server to "re-use" or "hydrate" the client side application.

Even if you do not use redux, the general concepts from the `feature/redux` branch still apply.

You want to fetch the critical data to run your app on the server and attach them to the `window` object. On the client side, you can use this data to populate a component's internal state.

An example could be

```
<!-- EJS -->
<script>
  window.__TIMER_STATE__ = <%= timerState =>;
</script>
```

```
// Timer component
class Timer extends Component {
  constructor() {
    this.state = window.__TIMER_STATE__;
    delete window.__TIMER_STATE__;
  }
}
```

The `timerState` would be passed down to the EJS by the server and contains an object with your fetch results.

Let me know, if this helps and/or refer to the redux branch for conceptional insight.

**Comment by manish4781** [comment]
Hey @rherwig thanks, this worked for me, although i have 2 question here.
1) is it safe to put all data on window object, in some cases this may be really large chunks of data.
2) is there a way i can hide the data on window object, 
what is the use of this **delete window.__TIMER_STATE__;**

**Comment by rherwig** [comment]
Glad it worked!

1. This is considered best practice for hydrating apps with server side data. But you are not wrong: the more data, the longer the page takes to parse. This is why you should only provide the minimum required data for the requested page to work via window. 
You could even populate the window object with different data, depending on the page the user requests.

2. This is done, to avoid cluttering the window object at runtime, since it is generally discouraged to make data globally available via window. This is what we use data stores for. Also: when using hot-reloading, there might be the issue of hydrating your app multiple times with the window data, thus overriding the current app state. Deleting the server-state from the window works around this.

**Comment by manish4781** [comment]
looks good, thanks.
