### ISSUE TITLE
add styles to template

### ISSUE THREAD

**Issue by manish4781** [rherwig/template-react-16-ssr#29]
just wanted to know how can i add .css(styl) file directly to .ejs,
i tried adding it to ejs by keeping my file is public directory but say file not found, so what is the best way to add some style globally?

**Comment by crabbits** [comment]
Hi @manish4781, can you post an example of how you are trying to add the css to the .ejs file? Also is the css file coming from a node module you have installed? Or a css file you've imported?

**Comment by manish4781** [comment]
Hi @crabbits, i have a custom css(.styl) file which i want to include globally in my .ejs file as stylesheet,
currently i am able to import any .styl file in my component but once imported styles looks like 
**.header.AhHeader__ah-header--3xvST {
  max-width: 1080px;
}**
so my question is where do i keep my css and how do i import as stylesheet in .ejs file

**Comment by rherwig** [comment]
@manish4781 The question arose some time ago, but I would generally discourage the use of stylesheets in the ejs file. Import the styles in your components, since you can benefit from the dynamic class names and bundling that way.

Check out the latest release of the template, which happens to abolish ejs files in favor of html in js.
